### ISSUE TITLE
checkmate all inputs

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgmatch#32]
## TODO

- [x] `pkgmatch_similar_pkgs()`
- [x] `pkgmatch_similar_fns()`
- [x] `pkgmatch_bm25()`
- [x] `pkgmatch_bm25_fn_calls()`
- [x] `pkgmatch_browse()`
- [x] `pkgmatch_embeddings_from_pkgs()`
- [x] `pkgmatch_embeddings_from_text()`
- [x] `pkgmatch_load_data()`
- [x] `pkgmatch_treesitter_fn_tags()`
- [x] `text_is_code()`
